---

- name: create dest dir for files
  file:
    path: /tmp/{{cluster_name}}/testapp
    state: directory

- name: create templates
  template:
    src: "{{item}}"
    dest: /tmp/{{cluster_name}}/testapp
  with_fileglob: "{{role_path}}/templates/*.yaml"

- name: get files in testapp
  find:
    paths: /tmp/{{cluster_name}}/testapp
    file_type: file
    patterns: '*.yaml,*.yml'
  register: yaml_list

- name: apply yaml manifests
  kubernetes.core.k8s:
    kubeconfig: "{{remote_kubeconfig}}"
    state: present
    src: "{{item.path}}"
    namespace: default
  loop: "{{yaml_list.files}}"


- name: create test curl script
  template:
    src: "{{item}}"
    dest: .
    owner: ubuntu
    mode: 0775
  loop:
    - test-curl.sh
    - test-curl-public.sh

