---

- name: copy gcloud register installer script
  copy:
    src: gcloud_register_cluster.sh
    dest: .
    mode: 0755

- name: run gcloud register install script
  command:
    cmd: ./gcloud_register_cluster.sh {{asm_type}} {{asm_version}} {{asm_release_channel}} {{cluster_type}} {{cluster_name}} {{project_id}} {{region}} {{is_regional_cluster}}
  register: register_cluster
- debug: msg="{{register_cluster.stdout_lines}}"
