---

- name: set tf-creator service accound for gcloud
  command:
    cmd: gcloud auth activate-service-account tf-creator@{{project_id}}.iam.gserviceaccount.com --key-file=tf-creator.json
  register: activate_svc_account
- name: set gcp project id
  command:
    cmd: gcloud config set project {{project_id}}


- name: copy ASM installer script
  copy:
    src: install_asm.sh
    dest: .
    mode: 0755

- name: run ASM install script
  command:
    cmd: ./install_asm.sh {{asm_type}} {{asm_version}} {{asm_release_channel}} {{cluster_type}} {{cluster_name}} {{project_id}} {{region}} {{is_regional_cluster}}
  register: asm_install
- debug: msg="{{asm_install}}"
