---

- name: copy tiny-tools DS file to remote host
  copy:
    src: "{{role_path}}/files/tiny-tools-daemonset.yaml"
    dest: .
    owner: ubuntu
    group: ubuntu

- name: apply tiny tools daemonset
  k8s:
    kubeconfig: "{{remote_kubeconfig}}"
    state: present
    src: tiny-tools-daemonset.yaml
    namespace: default

