apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: ingress-backendconfig
  namespace: asm-gateways
spec:
  healthCheck:
    requestPath: /healthz/ready
    port: 15021
    type: HTTP
  # https://cloud.google.com/architecture/exposing-service-mesh-apps-through-gke-ingress#apply_backend_service_settings
  # gcloud compute security-policies create edge-fw-policy --description "Block XSS attacks"
  # gcloud compute security-policies rules create 1000 --security-policy edge-fw-policy --expression "evaluatePreconfiguredExpr('xss-stable')" --action "deny-403" --description "XSS attack filtering"
  #
  # for Cloud Armor policy
  #securityPolicy:
  #  name: edge-fw-policy
