---

- name: create dest dir for files
  file:
    path: /tmp/{{cluster_name}}
    state: directory

- name: copy files
  copy:
    src: "{{role_path}}/templates/{{item}}"
    dest: /tmp/{{cluster_name}}
  loop:
    - ingress-backendconfig.yaml
    - ingress.yaml

- name: create templates
  template:
    src: "{{item}}"
    dest: /tmp/{{cluster_name}}
  loop:
    - ingress.yaml
    - ingress-backendconfig.yaml

- name: Ensure the default Namespace exists.
  kubernetes.core.k8s:
    kubeconfig: "{{remote_kubeconfig}}"
    api_version: v1
    kind: Namespace
    name: asm-gateways
    state: present

- name: apply yaml manifests
  kubernetes.core.k8s:
    kubeconfig: "{{remote_kubeconfig}}"
    state: present
    src: /tmp/{{cluster_name}}/ingress.yaml
    namespace: asm-gateways

- name: apply yaml manifests
  kubernetes.core.k8s:
    kubeconfig: "{{remote_kubeconfig}}"
    state: present
    src: /tmp/{{cluster_name}}/ingress-backendconfig.yaml
    namespace: asm-gateways


