---

- name: set logging level for Cloud Armor security policy rule, this option not exposed from terraform
  command:
    cmd: "gcloud compute security-policies update {{cluster_name}}-security-policy --log-level=VERBOSE"

# use either: 1) container native routing direct to service 2) OR point at istiod ingressgateway
- set_fact:
    file_prefix_primary: "{{ https_lb_primary_container_native_routing | ternary('cnr-','') }}"
- set_fact:
    file_prefix_secondary: "{{ https_lb_secondary_container_native_routing | ternary('cnr-','') }}"

- name: create dest dir for files
  file:
    path: /tmp/{{cluster_name}}/lb
    state: directory

- name: create ingress template
  template:
    src: "{{item}}"
    dest: /tmp/{{cluster_name}}/lb
  loop:
    - "{{file_prefix_primary}}ingress.yaml"
    - "{{file_prefix_secondary}}ingress-int.yaml"

- name: Ensure the Namespace exists
  kubernetes.core.k8s:
    kubeconfig: "{{remote_kubeconfig}}"
    api_version: v1
    kind: Namespace
    name: "{{ ingress_namespace }}"
    state: present

- name: apply yaml manifests for primary external HTTPS LB (if enabled)
  kubernetes.core.k8s:
    kubeconfig: "{{remote_kubeconfig}}"
    state: present
    src: /tmp/{{cluster_name}}/lb/{{file_prefix_primary}}ingress.yaml
    namespace: "{{ ingress_namespace }}"
  when: https_lb_primary

- name: apply yaml manifests for secondary internal HTTPS LB (if enabled)
  kubernetes.core.k8s:
    kubeconfig: "{{remote_kubeconfig}}"
    state: present
    src: /tmp/{{cluster_name}}/lb/{{file_prefix_secondary}}ingress-int.yaml
    namespace: "{{ ingress_namespace }}"
  when: https_lb_secondary
