---

- name: create ssl policy for load balancer
  command:
    cmd: "gcloud compute ssl-policies create {{cluster_name}}-ssl-policy --min-tls-version=1.2 --profile=MODERN"
  register: create_sslpolicy
  failed_when: create_sslpolicy.rc!=0 and not "already exists" in create_sslpolicy.stderr
- debug: msg="{{create_sslpolicy}}"

- name: create security-policy for Cloud Armor
  command:
    cmd: "gcloud compute security-policies create {{cluster_name}}-security-policy --description \"Cloud Armor security policy\""
  register: create_secpol
  failed_when: create_secpol.rc!=0 and not "already exists" in create_secpol.stderr

- debug: msg="{{create_secpol}}"

- name: set logging for rule
  command:
    cmd: "gcloud compute security-policies update {{cluster_name}}-security-policy --log-level=VERBOSE"

- name: update security rule with XSS
  command:
    cmd: "gcloud compute security-policies rules create 1000 --security-policy {{cluster_name}}-security-policy --expression \"evaluatePreconfiguredExpr('xss-stable')\" --action deny-403 --description \"XSS attack filtering\""
  register: update_output
  failed_when: update_output.rc!=0 and not "rules with the same priorities" in update_output.stderr
- debug: msg="{{update_output}}"

- name: update security rule with DDOS
  command:
    cmd: "gcloud beta compute security-policies update {{cluster_name}}-security-policy --enable-layer7-ddos-defense"
  register: update_output
- debug: msg="{{update_output}}"


# use container native routing (cnr) direct to service OR send to istiod ingressgateway
- set_fact:
    file_prefix: "{{ https_lb_container_native_routing | ternary('cnr-','') }}"

- name: create dest dir for files
  file:
    path: /tmp/{{cluster_name}}/lb
    state: directory

- name: create ingress template
  template:
    src: "{{item}}"
    dest: /tmp/{{cluster_name}}/lb
  loop:
    - "{{file_prefix}}ingress.yaml"

- name: Ensure the Namespace exists
  kubernetes.core.k8s:
    kubeconfig: "{{remote_kubeconfig}}"
    api_version: v1
    kind: Namespace
    name: "{{ ingress_namespace }}"
    state: present

- name: apply yaml manifests
  kubernetes.core.k8s:
    kubeconfig: "{{remote_kubeconfig}}"
    state: present
    src: /tmp/{{cluster_name}}/lb/{{file_prefix}}ingress.yaml
    namespace: "{{ ingress_namespace }}"


