# set authentication using service account json file, and set project
---

- name: set tf-creator service accound for gcloud
  command:
    cmd: gcloud auth activate-service-account tf-creator@{{project_id}}.iam.gserviceaccount.com --key-file=tf-creator.json
  register: activate_svc_account

- name: set gcp project id
  command:
    cmd: gcloud config set project {{project_id}}

