# backend for secondary istiod Ingress Gateway that defines health check and Cloud Armor policy
# referenced in: istio-ingressgateway-int/service.yaml
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: ingress-backendconfig-int
spec:
  healthCheck:
    requestPath: /healthz/ready
    port: 15021
    type: HTTP
  # Cloud Armor policy not compatible with Internal HTTPS LB
  #securityPolicy:

