apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: ingress-backendconfig-int
  #namespace: asm-gateways
spec:
  healthCheck:
    requestPath: /healthz/ready
    port: 15022
    type: HTTP
