# ingress gateway for private internal services
apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway-int
  labels:
    app: istio-ingressgateway-int
    istio: ingressgateway-int
  annotations:
    # internal TCP LB without NEG
    cloud.google.com/neg: '{"ingress": false}'
    cloud.google.com/app-protocols: '{"https":"HTTPS"}'
    cloud.google.com/load-balancer-type: "Internal"
    networking.gke.io/suppress-firewall-xpn-error: "true"
    kubernetes.io/ingress.class: istio-int
spec:
  loadBalancerIP: {{subnet_prefix}}.199
  loadBalancerSourceRanges: [ 10.0.0.0/8 ]
  ports:
  # status-port exposes a /healthz/ready endpoint that can be used with GKE Ingress health checks
  - name: status-port
    port: 15022
    protocol: TCP
    targetPort: 15022
  # Any ports exposed in Gateway resources should be exposed here.
  - name: http2
    port: 80
  - name: https
    port: 443
  selector:
    istio: ingressgateway-int
    app: istio-ingressgateway-int
  type: LoadBalancer
