# https://wdenniss.com/gke-autopilot-spare-capacity
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: balloon-priority
  value: -10 # undocumented lowest priority that will trigger upscale
  preemptionPolicy: Never
  globalDefault: false
  description: "Balloon pod priority."
