# you can get the proper form by doing a dry-run
# kubectl create secret tls test-credential --cert=my.crt --key=my.key --dry-run=client --output=yaml
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  #creationTimestamp: null
  name: "{{secret_name}}"
data:
  tls.crt: "{{CERT_BASE64.content}}"
  tls.key: "{{KEY_BASE64.content}}"

