---

- name: set gcloud login context with service account
  include_role:
    name: gcloud-use-serviceaccount
    tasks_from: main

- name: tiny tools daemonset
  k8s:
    kubeconfig: "{{remote_kubeconfig}}"
    state: present
    src: tiny-tools-daemonset.yaml

