---

- name: set tf-creator service accound for gcloud
  command:
    cmd: gcloud auth activate-service-account tf-creator@{{project_id}}.iam.gserviceaccount.com --key-file=tf-creator.json
  register: activate_svc_account
- name: set gcp project id
  command:
    cmd: gcloud config set project {{project_id}}


- name: mkdir for balloon yaml
  file:
    state: directory
    path: /tmp/{{cluster_name}}/balloon

- name: create templates
  template:
    src: "{{item}}"
    dest: /tmp/{{cluster_name}}/balloon
  loop:
    - balloon-priority.yaml
    - balloon.yaml

- name: apply yaml manifests
  kubernetes.core.k8s:
    kubeconfig: "{{remote_kubeconfig}}"
    state: present
    src: /tmp/{{cluster_name}}/balloon/{{item}}
    namespace: default
  loop:
    - balloon-priority.yaml
    - balloon.yaml
