---
# frontend that defines redirector for http->https and TLS 1.2+ policy
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: lb-http-to-https
  #namespace: "{{ingress_namespace}}"
spec:
  redirectToHttps:
    enabled: true
  # need to create ssl-policies, https://cloud.google.com/load-balancing/docs/use-ssl-policies#creating_ssl_policies
  # 'gcloud compute ssl-policies'
  sslPolicy: {{cluster_name}}-ssl-policy
---
# for container native load balancing, each service has BackendConfig
# that defines health check and security policy, so not defined here
#
# if this was non container-native load balancing, then
# we would define a backend to the istiod service and would
# add a backend to its health check (/healthz/ready) and status port
# referenced in: roles/ASM-IngressGateway/templates/istio-ingressgateway/service.yaml
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  #namespace: "{{ingress_namespace}}"
  annotations:
    # If the class annotation is not specified it defaults to "gce".
    kubernetes.io/ingress.class: gce
    # name of global static IP, will default to using public ephemeral if this does not exist
    #kubernetes.io/ingress.global-static-ip-name: {{cluster_name}}-global
    kubernetes.io/ingress.allow-http: "false"
    networking.gke.io/v1beta1.FrontendConfig: lb-http-to-https
spec:
#  defaultBackend:
#    service:
#      name: golang-hello-world-web-service
#      port:
#        number: 8080

  tls:
  - secretName: {{cluster_name}}-tls-secret

  rules:
  - http:
      paths:
      - path: /myhello/*
        pathType: ImplementationSpecific
        backend:
          service:
            name: golang-hello-world-web-service
            port:
              number: 8080
# ADDTITIONAL services could be added here
#      - path: /myint/*
#        pathType: ImplementationSpecific
#        backend:
#          service:
#            name: golang-hello-world-web-int-service
#            port:
#              number: 8080
