---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: lb-http-to-https
  namespace: asm-gateways
spec:
  redirectToHttps:
    enabled: true
---
# https://cloud.google.com/kubernetes-engine/docs/how-to/load-balance-ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  namespace: asm-gateways
  annotations:
    # If the class annotation is not specified it defaults to "gce".
    kubernetes.io/ingress.class: gce
    # name of global static IP, will default to using public ephemeral if this does not exist
    #kubernetes.io/ingress.global-static-ip-name: {{cluster_name}}-global
    kubernetes.io/ingress.allow-http: "true"
    networking.gke.io/v1beta1.FrontendConfig: lb-http-to-https
spec:
  #defaultBackend:
  #  service:
  #    name: istio-ingressgateway
  #    port:
  #      number: 80

  tls:
  - secretName: {{cluster_name}}-tls-secret

  rules:
  - http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: istio-ingressgateway
            port:
              number: 443
              # served up http good
              #number: 80
