---

- name: set tf-creator service accound for gcloud
  command:
    cmd: gcloud auth activate-service-account tf-creator@{{project_id}}.iam.gserviceaccount.com --key-file=tf-creator.json
  register: activate_svc_account
- name: set gcp project id
  command:
    cmd: gcloud config set project {{project_id}}


- name: create dest dir for files
  file:
    path: /tmp/{{cluster_name}}/testapp
    state: directory

- name: create templates
  template:
    src: "{{item}}"
    dest: /tmp/{{cluster_name}}/testapp
  with_fileglob: "{{role_path}}/templates/*.yaml"

- name: get files in testapp
  find:
    paths: /tmp/{{cluster_name}}/testapp
    file_type: file
    patterns: '*.yaml,*.yml'
  register: yaml_list

- name: apply yaml manifests
  kubernetes.core.k8s:
    kubeconfig: "{{remote_kubeconfig}}"
    state: present
    src: "{{item.path}}"
    namespace: default
  loop: "{{yaml_list.files}}"
