apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: ingress-backendconfig
  #namespace: default
spec:
  healthCheck:
    requestPath: /healthz/ready
    port: 15021
    type: HTTP
  # Cloud Armor policy
  securityPolicy:
    name: "{{cluster_name}}-security-policy"

