# ingress gateway for public services
apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
  annotations:
    # https://cloud.google.com/architecture/exposing-service-mesh-apps-through-gke-ingress#install_an_ingress_gateway
    # need NEG to make k8s-ig-- backend connections healthy
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/app-protocols: '{"https":"HTTPS"}'

    cloud.google.com/load-balancer-type: "Internal" # TCP LB

    networking.gke.io/suppress-firewall-xpn-error: "true"
    kubernetes.io/ingress.class: istio

    # this backend config is not necessary for TCP LB, but it is for HTTPS LB
    # without this backend health check, the front-facing GCP HTTPS LB will not be healthy
    # needed whether or not using container native routing
    cloud.google.com/backend-config: '{"default": "ingress-backendconfig"}'
spec:
  loadBalancerIP: {{subnet_prefix}}.198
  loadBalancerSourceRanges: [ 10.0.0.0/8 ]
  ports:
  # status-port exposes a /healthz/ready endpoint that can be used with GKE Ingress health checks
  - name: status-port
    port: 15021
    protocol: TCP
    targetPort: 15021
  # Any ports exposed in Gateway resources should be exposed here.
  - name: http2
    port: 80
  - name: https
    port: 443
  selector:
    istio: ingressgateway
    app: istio-ingressgateway
  type: LoadBalancer
