---

- hosts: localhost
  connection: local
  tasks:
    # sed 's/cmd-path: .*gcloud$/cmd-path: gcloud/' kubeconfig-xxx
    - name: strip out full gcloud binary path in cmd-path to allow portability to another host
      lineinfile:
        path: "{{item}}"
        regexp: '^(\s*)cmd-path: .*gcloud$'
        line: '\1cmd-path: gcloud'
        backrefs: yes
        backup: no
      with_fileglob: "{{playbook_dir}}/../kubeconfig-*"

- hosts: jumpboxes
  become: yes
  tasks:
    - name: copy kubeconfig files remotely
      copy:
        src: "{{item}}"
        dest: "."
        mode: 0660
        owner: ubuntu
        group: ubuntu
      with_fileglob: "{{playbook_dir}}/../kubeconfig-*"

