---

- hosts: jumpboxes
  become: yes
  tasks:
    - name: copy kubeconfig files remotely
      copy:
        src: "{{item}}"
        dest: "."
        mode: 0660
        owner: ubuntu
        group: ubuntu
      with_fileglob: "{{playbook_dir}}/../kubeconfig-*"
